services:
  postgres:
    image: postgres:17
    container_name: wallet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DigitalWalletDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d DigitalWalletDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wallet-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=DigitalWalletDb;Username=postgres;Password=admin
      - RabbitMQ__Host=rabbitmq
      - JwtSettings__Secret=ThiskeyissecretAtLeast32CharAndImGoingToBeADeveloper
      - JwtSettings__Issuer=DigitalWalletApi
      - JwtSettings__Audience=DigitalWalletApp
      - JwtSettings__ExpiryMinutes=60
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=DigitalWalletDb;Username=postgres;Password=admin
      - RabbitMQ__Host=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data: